[package]
name = "toy-lang"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0.44"
combine = "4.6.1"

[dev-dependencies]
test-case = "1.2.0"

[[bin]]
name = "toy"
test = false
bench = false
